// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: drone.proto

package dronepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      float64                `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	PointOrder    int32                  `protobuf:"varint,4,opt,name=point_order,json=pointOrder,proto3" json:"point_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_drone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_drone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_drone_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Coordinate) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *Coordinate) GetPointOrder() int32 {
	if x != nil {
		return x.PointOrder
	}
	return 0
}

type CoordinatesBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroneId       int32                  `protobuf:"varint,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Coordinates   []*Coordinate          `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatesBatchRequest) Reset() {
	*x = CoordinatesBatchRequest{}
	mi := &file_drone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatesBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatesBatchRequest) ProtoMessage() {}

func (x *CoordinatesBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatesBatchRequest.ProtoReflect.Descriptor instead.
func (*CoordinatesBatchRequest) Descriptor() ([]byte, []int) {
	return file_drone_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinatesBatchRequest) GetDroneId() int32 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *CoordinatesBatchRequest) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type CoordinatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatesResponse) Reset() {
	*x = CoordinatesResponse{}
	mi := &file_drone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatesResponse) ProtoMessage() {}

func (x *CoordinatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatesResponse.ProtoReflect.Descriptor instead.
func (*CoordinatesResponse) Descriptor() ([]byte, []int) {
	return file_drone_proto_rawDescGZIP(), []int{2}
}

func (x *CoordinatesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_drone_proto protoreflect.FileDescriptor

const file_drone_proto_rawDesc = "" +
	"\n" +
	"\vdrone.proto\x12\x05drone\"\x83\x01\n" +
	"\n" +
	"Coordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x03 \x01(\x01R\baltitude\x12\x1f\n" +
	"\vpoint_order\x18\x04 \x01(\x05R\n" +
	"pointOrder\"i\n" +
	"\x17CoordinatesBatchRequest\x12\x19\n" +
	"\bdrone_id\x18\x01 \x01(\x05R\adroneId\x123\n" +
	"\vcoordinates\x18\x02 \x03(\v2\x11.drone.CoordinateR\vcoordinates\"-\n" +
	"\x13CoordinatesResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2]\n" +
	"\fDroneService\x12M\n" +
	"\x0fSendCoordinates\x12\x1e.drone.CoordinatesBatchRequest\x1a\x1a.drone.CoordinatesResponseB\x19Z\x17backend/dronepb;dronepbb\x06proto3"

var (
	file_drone_proto_rawDescOnce sync.Once
	file_drone_proto_rawDescData []byte
)

func file_drone_proto_rawDescGZIP() []byte {
	file_drone_proto_rawDescOnce.Do(func() {
		file_drone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drone_proto_rawDesc), len(file_drone_proto_rawDesc)))
	})
	return file_drone_proto_rawDescData
}

var file_drone_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_drone_proto_goTypes = []any{
	(*Coordinate)(nil),              // 0: drone.Coordinate
	(*CoordinatesBatchRequest)(nil), // 1: drone.CoordinatesBatchRequest
	(*CoordinatesResponse)(nil),     // 2: drone.CoordinatesResponse
}
var file_drone_proto_depIdxs = []int32{
	0, // 0: drone.CoordinatesBatchRequest.coordinates:type_name -> drone.Coordinate
	1, // 1: drone.DroneService.SendCoordinates:input_type -> drone.CoordinatesBatchRequest
	2, // 2: drone.DroneService.SendCoordinates:output_type -> drone.CoordinatesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_drone_proto_init() }
func file_drone_proto_init() {
	if File_drone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drone_proto_rawDesc), len(file_drone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drone_proto_goTypes,
		DependencyIndexes: file_drone_proto_depIdxs,
		MessageInfos:      file_drone_proto_msgTypes,
	}.Build()
	File_drone_proto = out.File
	file_drone_proto_goTypes = nil
	file_drone_proto_depIdxs = nil
}
