# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drone.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'drone.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64rone.proto\x12\x05\x64rone\"X\n\nCoordinate\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\x12\x13\n\x0bpoint_order\x18\x04 \x01(\x05\"S\n\x17\x43oordinatesBatchRequest\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\x05\x12&\n\x0b\x63oordinates\x18\x02 \x03(\x0b\x32\x11.drone.Coordinate\"%\n\x13\x43oordinatesResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2]\n\x0c\x44roneService\x12M\n\x0fSendCoordinates\x12\x1e.drone.CoordinatesBatchRequest\x1a\x1a.drone.CoordinatesResponseB\x19Z\x17\x62\x61\x63kend/dronepb;dronepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drone_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027backend/dronepb;dronepb'
  _globals['_COORDINATE']._serialized_start=22
  _globals['_COORDINATE']._serialized_end=110
  _globals['_COORDINATESBATCHREQUEST']._serialized_start=112
  _globals['_COORDINATESBATCHREQUEST']._serialized_end=195
  _globals['_COORDINATESRESPONSE']._serialized_start=197
  _globals['_COORDINATESRESPONSE']._serialized_end=234
  _globals['_DRONESERVICE']._serialized_start=236
  _globals['_DRONESERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
