// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/fly_service.proto

package flight

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusUpdateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId   int32                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RejectionReason string                 `protobuf:"bytes,4,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusUpdateRequest) Reset() {
	*x = StatusUpdateRequest{}
	mi := &file_proto_fly_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdateRequest) ProtoMessage() {}

func (x *StatusUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdateRequest.ProtoReflect.Descriptor instead.
func (*StatusUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{0}
}

func (x *StatusUpdateRequest) GetApplicationId() int32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *StatusUpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusUpdateRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusUpdateRequest) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *StatusUpdateRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StatusUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdateResponse) Reset() {
	*x = StatusUpdateResponse{}
	mi := &file_proto_fly_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdateResponse) ProtoMessage() {}

func (x *StatusUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdateResponse.ProtoReflect.Descriptor instead.
func (*StatusUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{1}
}

func (x *StatusUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusUpdateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type FlightStartedRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId    int32                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	DroneId          int32                  `protobuf:"varint,2,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	PilotId          int32                  `protobuf:"varint,3,opt,name=pilot_id,json=pilotId,proto3" json:"pilot_id,omitempty"`
	Route            []*RoutePoint          `protobuf:"bytes,4,rep,name=route,proto3" json:"route,omitempty"`
	CurrentPosition  *DronePosition         `protobuf:"bytes,5,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	StartTime        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EstimatedEndTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=estimated_end_time,json=estimatedEndTime,proto3" json:"estimated_end_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FlightStartedRequest) Reset() {
	*x = FlightStartedRequest{}
	mi := &file_proto_fly_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightStartedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightStartedRequest) ProtoMessage() {}

func (x *FlightStartedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightStartedRequest.ProtoReflect.Descriptor instead.
func (*FlightStartedRequest) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{2}
}

func (x *FlightStartedRequest) GetApplicationId() int32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *FlightStartedRequest) GetDroneId() int32 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *FlightStartedRequest) GetPilotId() int32 {
	if x != nil {
		return x.PilotId
	}
	return 0
}

func (x *FlightStartedRequest) GetRoute() []*RoutePoint {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *FlightStartedRequest) GetCurrentPosition() *DronePosition {
	if x != nil {
		return x.CurrentPosition
	}
	return nil
}

func (x *FlightStartedRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *FlightStartedRequest) GetEstimatedEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedEndTime
	}
	return nil
}

type FlightStartedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightStartedResponse) Reset() {
	*x = FlightStartedResponse{}
	mi := &file_proto_fly_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightStartedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightStartedResponse) ProtoMessage() {}

func (x *FlightStartedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightStartedResponse.ProtoReflect.Descriptor instead.
func (*FlightStartedResponse) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{3}
}

func (x *FlightStartedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FlightStartedResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DronePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId int32                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	DroneId       int32                  `protobuf:"varint,2,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      float64                `protobuf:"fixed64,5,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Speed         float64                `protobuf:"fixed64,6,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,7,opt,name=heading,proto3" json:"heading,omitempty"`
	RouteProgress float64                `protobuf:"fixed64,8,opt,name=route_progress,json=routeProgress,proto3" json:"route_progress,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DronePositionRequest) Reset() {
	*x = DronePositionRequest{}
	mi := &file_proto_fly_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DronePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DronePositionRequest) ProtoMessage() {}

func (x *DronePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DronePositionRequest.ProtoReflect.Descriptor instead.
func (*DronePositionRequest) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{4}
}

func (x *DronePositionRequest) GetApplicationId() int32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *DronePositionRequest) GetDroneId() int32 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *DronePositionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DronePositionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DronePositionRequest) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *DronePositionRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *DronePositionRequest) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *DronePositionRequest) GetRouteProgress() float64 {
	if x != nil {
		return x.RouteProgress
	}
	return 0
}

func (x *DronePositionRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type DronePositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DronePositionResponse) Reset() {
	*x = DronePositionResponse{}
	mi := &file_proto_fly_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DronePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DronePositionResponse) ProtoMessage() {}

func (x *DronePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DronePositionResponse.ProtoReflect.Descriptor instead.
func (*DronePositionResponse) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{5}
}

func (x *DronePositionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DronePositionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type FlightCompletedRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId    int32                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	DroneId          int32                  `protobuf:"varint,2,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	FinalPosition    *DronePosition         `protobuf:"bytes,3,opt,name=final_position,json=finalPosition,proto3" json:"final_position,omitempty"`
	CompletionTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completion_time,json=completionTime,proto3" json:"completion_time,omitempty"`
	CompletionStatus string                 `protobuf:"bytes,5,opt,name=completion_status,json=completionStatus,proto3" json:"completion_status,omitempty"` // completed, cancelled, emergency_landing
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FlightCompletedRequest) Reset() {
	*x = FlightCompletedRequest{}
	mi := &file_proto_fly_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightCompletedRequest) ProtoMessage() {}

func (x *FlightCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightCompletedRequest.ProtoReflect.Descriptor instead.
func (*FlightCompletedRequest) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{6}
}

func (x *FlightCompletedRequest) GetApplicationId() int32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *FlightCompletedRequest) GetDroneId() int32 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *FlightCompletedRequest) GetFinalPosition() *DronePosition {
	if x != nil {
		return x.FinalPosition
	}
	return nil
}

func (x *FlightCompletedRequest) GetCompletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionTime
	}
	return nil
}

func (x *FlightCompletedRequest) GetCompletionStatus() string {
	if x != nil {
		return x.CompletionStatus
	}
	return ""
}

type FlightCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightCompletedResponse) Reset() {
	*x = FlightCompletedResponse{}
	mi := &file_proto_fly_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightCompletedResponse) ProtoMessage() {}

func (x *FlightCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightCompletedResponse.ProtoReflect.Descriptor instead.
func (*FlightCompletedResponse) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{7}
}

func (x *FlightCompletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FlightCompletedResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RestrictedZoneAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId int32                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	DroneId       int32                  `protobuf:"varint,2,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	ZoneName      string                 `protobuf:"bytes,3,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	ZoneLatitude  float64                `protobuf:"fixed64,4,opt,name=zone_latitude,json=zoneLatitude,proto3" json:"zone_latitude,omitempty"`
	ZoneLongitude float64                `protobuf:"fixed64,5,opt,name=zone_longitude,json=zoneLongitude,proto3" json:"zone_longitude,omitempty"`
	ZoneRadius    int32                  `protobuf:"varint,6,opt,name=zone_radius,json=zoneRadius,proto3" json:"zone_radius,omitempty"`
	AlertLevel    string                 `protobuf:"bytes,7,opt,name=alert_level,json=alertLevel,proto3" json:"alert_level,omitempty"` // INFO, WARNING, DANGER
	Distance      float64                `protobuf:"fixed64,8,opt,name=distance,proto3" json:"distance,omitempty"`
	DronePosition *DronePosition         `protobuf:"bytes,9,opt,name=drone_position,json=dronePosition,proto3" json:"drone_position,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestrictedZoneAlertRequest) Reset() {
	*x = RestrictedZoneAlertRequest{}
	mi := &file_proto_fly_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestrictedZoneAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestrictedZoneAlertRequest) ProtoMessage() {}

func (x *RestrictedZoneAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestrictedZoneAlertRequest.ProtoReflect.Descriptor instead.
func (*RestrictedZoneAlertRequest) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{8}
}

func (x *RestrictedZoneAlertRequest) GetApplicationId() int32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *RestrictedZoneAlertRequest) GetDroneId() int32 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *RestrictedZoneAlertRequest) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *RestrictedZoneAlertRequest) GetZoneLatitude() float64 {
	if x != nil {
		return x.ZoneLatitude
	}
	return 0
}

func (x *RestrictedZoneAlertRequest) GetZoneLongitude() float64 {
	if x != nil {
		return x.ZoneLongitude
	}
	return 0
}

func (x *RestrictedZoneAlertRequest) GetZoneRadius() int32 {
	if x != nil {
		return x.ZoneRadius
	}
	return 0
}

func (x *RestrictedZoneAlertRequest) GetAlertLevel() string {
	if x != nil {
		return x.AlertLevel
	}
	return ""
}

func (x *RestrictedZoneAlertRequest) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *RestrictedZoneAlertRequest) GetDronePosition() *DronePosition {
	if x != nil {
		return x.DronePosition
	}
	return nil
}

func (x *RestrictedZoneAlertRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RestrictedZoneAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestrictedZoneAlertResponse) Reset() {
	*x = RestrictedZoneAlertResponse{}
	mi := &file_proto_fly_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestrictedZoneAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestrictedZoneAlertResponse) ProtoMessage() {}

func (x *RestrictedZoneAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestrictedZoneAlertResponse.ProtoReflect.Descriptor instead.
func (*RestrictedZoneAlertResponse) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{9}
}

func (x *RestrictedZoneAlertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestrictedZoneAlertResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RoutePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      float64                `protobuf:"fixed64,4,opt,name=altitude,proto3" json:"altitude,omitempty"`
	PointOrder    int32                  `protobuf:"varint,5,opt,name=point_order,json=pointOrder,proto3" json:"point_order,omitempty"`
	ApplicationId int32                  `protobuf:"varint,6,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePoint) Reset() {
	*x = RoutePoint{}
	mi := &file_proto_fly_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePoint) ProtoMessage() {}

func (x *RoutePoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePoint.ProtoReflect.Descriptor instead.
func (*RoutePoint) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{10}
}

func (x *RoutePoint) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoutePoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RoutePoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RoutePoint) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *RoutePoint) GetPointOrder() int32 {
	if x != nil {
		return x.PointOrder
	}
	return 0
}

func (x *RoutePoint) GetApplicationId() int32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

type DronePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId int32                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	DroneId       int32                  `protobuf:"varint,2,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      float64                `protobuf:"fixed64,5,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Speed         float64                `protobuf:"fixed64,6,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,7,opt,name=heading,proto3" json:"heading,omitempty"`
	RouteProgress float64                `protobuf:"fixed64,8,opt,name=route_progress,json=routeProgress,proto3" json:"route_progress,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DronePosition) Reset() {
	*x = DronePosition{}
	mi := &file_proto_fly_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DronePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DronePosition) ProtoMessage() {}

func (x *DronePosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fly_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DronePosition.ProtoReflect.Descriptor instead.
func (*DronePosition) Descriptor() ([]byte, []int) {
	return file_proto_fly_service_proto_rawDescGZIP(), []int{11}
}

func (x *DronePosition) GetApplicationId() int32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *DronePosition) GetDroneId() int32 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *DronePosition) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DronePosition) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DronePosition) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *DronePosition) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *DronePosition) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *DronePosition) GetRouteProgress() float64 {
	if x != nil {
		return x.RouteProgress
	}
	return 0
}

func (x *DronePosition) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_fly_service_proto protoreflect.FileDescriptor

const file_proto_fly_service_proto_rawDesc = "" +
	"\n" +
	"\x17proto/fly_service.proto\x12\x06flight\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\x13StatusUpdateRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x05R\rapplicationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12)\n" +
	"\x10rejection_reason\x18\x04 \x01(\tR\x0frejectionReason\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"U\n" +
	"\x14StatusUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xe4\x02\n" +
	"\x14FlightStartedRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x05R\rapplicationId\x12\x19\n" +
	"\bdrone_id\x18\x02 \x01(\x05R\adroneId\x12\x19\n" +
	"\bpilot_id\x18\x03 \x01(\x05R\apilotId\x12(\n" +
	"\x05route\x18\x04 \x03(\v2\x12.flight.RoutePointR\x05route\x12@\n" +
	"\x10current_position\x18\x05 \x01(\v2\x15.flight.DronePositionR\x0fcurrentPosition\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12H\n" +
	"\x12estimated_end_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10estimatedEndTime\"V\n" +
	"\x15FlightStartedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xbf\x02\n" +
	"\x14DronePositionRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x05R\rapplicationId\x12\x19\n" +
	"\bdrone_id\x18\x02 \x01(\x05R\adroneId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x05 \x01(\x01R\baltitude\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\a \x01(\x01R\aheading\x12%\n" +
	"\x0eroute_progress\x18\b \x01(\x01R\rrouteProgress\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"V\n" +
	"\x15DronePositionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x8a\x02\n" +
	"\x16FlightCompletedRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x05R\rapplicationId\x12\x19\n" +
	"\bdrone_id\x18\x02 \x01(\x05R\adroneId\x12<\n" +
	"\x0efinal_position\x18\x03 \x01(\v2\x15.flight.DronePositionR\rfinalPosition\x12C\n" +
	"\x0fcompletion_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionTime\x12+\n" +
	"\x11completion_status\x18\x05 \x01(\tR\x10completionStatus\"X\n" +
	"\x17FlightCompletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x9d\x03\n" +
	"\x1aRestrictedZoneAlertRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x05R\rapplicationId\x12\x19\n" +
	"\bdrone_id\x18\x02 \x01(\x05R\adroneId\x12\x1b\n" +
	"\tzone_name\x18\x03 \x01(\tR\bzoneName\x12#\n" +
	"\rzone_latitude\x18\x04 \x01(\x01R\fzoneLatitude\x12%\n" +
	"\x0ezone_longitude\x18\x05 \x01(\x01R\rzoneLongitude\x12\x1f\n" +
	"\vzone_radius\x18\x06 \x01(\x05R\n" +
	"zoneRadius\x12\x1f\n" +
	"\valert_level\x18\a \x01(\tR\n" +
	"alertLevel\x12\x1a\n" +
	"\bdistance\x18\b \x01(\x01R\bdistance\x12<\n" +
	"\x0edrone_position\x18\t \x01(\v2\x15.flight.DronePositionR\rdronePosition\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\\\n" +
	"\x1bRestrictedZoneAlertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xba\x01\n" +
	"\n" +
	"RoutePoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x04 \x01(\x01R\baltitude\x12\x1f\n" +
	"\vpoint_order\x18\x05 \x01(\x05R\n" +
	"pointOrder\x12%\n" +
	"\x0eapplication_id\x18\x06 \x01(\x05R\rapplicationId\"\xb8\x02\n" +
	"\rDronePosition\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x05R\rapplicationId\x12\x19\n" +
	"\bdrone_id\x18\x02 \x01(\x05R\adroneId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x05 \x01(\x01R\baltitude\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\a \x01(\x01R\aheading\x12%\n" +
	"\x0eroute_progress\x18\b \x01(\x01R\rrouteProgress\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xd8\x03\n" +
	"\x19FlightNotificationService\x12O\n" +
	"\x12NotifyStatusUpdate\x12\x1b.flight.StatusUpdateRequest\x1a\x1c.flight.StatusUpdateResponse\x12R\n" +
	"\x13NotifyFlightStarted\x12\x1c.flight.FlightStartedRequest\x1a\x1d.flight.FlightStartedResponse\x12R\n" +
	"\x13UpdateDronePosition\x12\x1c.flight.DronePositionRequest\x1a\x1d.flight.DronePositionResponse\x12X\n" +
	"\x15NotifyFlightCompleted\x12\x1e.flight.FlightCompletedRequest\x1a\x1f.flight.FlightCompletedResponse\x12h\n" +
	"\x1dNotifyRestrictedZoneProximity\x12\".flight.RestrictedZoneAlertRequest\x1a#.flight.RestrictedZoneAlertResponseB3Z1github.com/nxbodyevzncvre/decenthack/proto/flightb\x06proto3"

var (
	file_proto_fly_service_proto_rawDescOnce sync.Once
	file_proto_fly_service_proto_rawDescData []byte
)

func file_proto_fly_service_proto_rawDescGZIP() []byte {
	file_proto_fly_service_proto_rawDescOnce.Do(func() {
		file_proto_fly_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fly_service_proto_rawDesc), len(file_proto_fly_service_proto_rawDesc)))
	})
	return file_proto_fly_service_proto_rawDescData
}

var file_proto_fly_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_fly_service_proto_goTypes = []any{
	(*StatusUpdateRequest)(nil),         // 0: flight.StatusUpdateRequest
	(*StatusUpdateResponse)(nil),        // 1: flight.StatusUpdateResponse
	(*FlightStartedRequest)(nil),        // 2: flight.FlightStartedRequest
	(*FlightStartedResponse)(nil),       // 3: flight.FlightStartedResponse
	(*DronePositionRequest)(nil),        // 4: flight.DronePositionRequest
	(*DronePositionResponse)(nil),       // 5: flight.DronePositionResponse
	(*FlightCompletedRequest)(nil),      // 6: flight.FlightCompletedRequest
	(*FlightCompletedResponse)(nil),     // 7: flight.FlightCompletedResponse
	(*RestrictedZoneAlertRequest)(nil),  // 8: flight.RestrictedZoneAlertRequest
	(*RestrictedZoneAlertResponse)(nil), // 9: flight.RestrictedZoneAlertResponse
	(*RoutePoint)(nil),                  // 10: flight.RoutePoint
	(*DronePosition)(nil),               // 11: flight.DronePosition
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
}
var file_proto_fly_service_proto_depIdxs = []int32{
	12, // 0: flight.StatusUpdateRequest.timestamp:type_name -> google.protobuf.Timestamp
	10, // 1: flight.FlightStartedRequest.route:type_name -> flight.RoutePoint
	11, // 2: flight.FlightStartedRequest.current_position:type_name -> flight.DronePosition
	12, // 3: flight.FlightStartedRequest.start_time:type_name -> google.protobuf.Timestamp
	12, // 4: flight.FlightStartedRequest.estimated_end_time:type_name -> google.protobuf.Timestamp
	12, // 5: flight.DronePositionRequest.timestamp:type_name -> google.protobuf.Timestamp
	11, // 6: flight.FlightCompletedRequest.final_position:type_name -> flight.DronePosition
	12, // 7: flight.FlightCompletedRequest.completion_time:type_name -> google.protobuf.Timestamp
	11, // 8: flight.RestrictedZoneAlertRequest.drone_position:type_name -> flight.DronePosition
	12, // 9: flight.RestrictedZoneAlertRequest.timestamp:type_name -> google.protobuf.Timestamp
	12, // 10: flight.DronePosition.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 11: flight.FlightNotificationService.NotifyStatusUpdate:input_type -> flight.StatusUpdateRequest
	2,  // 12: flight.FlightNotificationService.NotifyFlightStarted:input_type -> flight.FlightStartedRequest
	4,  // 13: flight.FlightNotificationService.UpdateDronePosition:input_type -> flight.DronePositionRequest
	6,  // 14: flight.FlightNotificationService.NotifyFlightCompleted:input_type -> flight.FlightCompletedRequest
	8,  // 15: flight.FlightNotificationService.NotifyRestrictedZoneProximity:input_type -> flight.RestrictedZoneAlertRequest
	1,  // 16: flight.FlightNotificationService.NotifyStatusUpdate:output_type -> flight.StatusUpdateResponse
	3,  // 17: flight.FlightNotificationService.NotifyFlightStarted:output_type -> flight.FlightStartedResponse
	5,  // 18: flight.FlightNotificationService.UpdateDronePosition:output_type -> flight.DronePositionResponse
	7,  // 19: flight.FlightNotificationService.NotifyFlightCompleted:output_type -> flight.FlightCompletedResponse
	9,  // 20: flight.FlightNotificationService.NotifyRestrictedZoneProximity:output_type -> flight.RestrictedZoneAlertResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_fly_service_proto_init() }
func file_proto_fly_service_proto_init() {
	if File_proto_fly_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fly_service_proto_rawDesc), len(file_proto_fly_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fly_service_proto_goTypes,
		DependencyIndexes: file_proto_fly_service_proto_depIdxs,
		MessageInfos:      file_proto_fly_service_proto_msgTypes,
	}.Build()
	File_proto_fly_service_proto = out.File
	file_proto_fly_service_proto_goTypes = nil
	file_proto_fly_service_proto_depIdxs = nil
}
