// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/drone.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DroneService_GetApplication_FullMethodName = "/drone.DroneService/GetApplication"
	DroneService_SimulateFlight_FullMethodName = "/drone.DroneService/SimulateFlight"
)

// DroneServiceClient is the client API for DroneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DroneServiceClient interface {
	GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*ApplicationResponse, error)
	SimulateFlight(ctx context.Context, in *FlightSimulationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Coordinates], error)
}

type droneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDroneServiceClient(cc grpc.ClientConnInterface) DroneServiceClient {
	return &droneServiceClient{cc}
}

func (c *droneServiceClient) GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*ApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationResponse)
	err := c.cc.Invoke(ctx, DroneService_GetApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) SimulateFlight(ctx context.Context, in *FlightSimulationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Coordinates], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DroneService_ServiceDesc.Streams[0], DroneService_SimulateFlight_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FlightSimulationRequest, Coordinates]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DroneService_SimulateFlightClient = grpc.ServerStreamingClient[Coordinates]

// DroneServiceServer is the server API for DroneService service.
// All implementations must embed UnimplementedDroneServiceServer
// for forward compatibility.
type DroneServiceServer interface {
	GetApplication(context.Context, *GetApplicationRequest) (*ApplicationResponse, error)
	SimulateFlight(*FlightSimulationRequest, grpc.ServerStreamingServer[Coordinates]) error
	mustEmbedUnimplementedDroneServiceServer()
}

// UnimplementedDroneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDroneServiceServer struct{}

func (UnimplementedDroneServiceServer) GetApplication(context.Context, *GetApplicationRequest) (*ApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplication not implemented")
}
func (UnimplementedDroneServiceServer) SimulateFlight(*FlightSimulationRequest, grpc.ServerStreamingServer[Coordinates]) error {
	return status.Errorf(codes.Unimplemented, "method SimulateFlight not implemented")
}
func (UnimplementedDroneServiceServer) mustEmbedUnimplementedDroneServiceServer() {}
func (UnimplementedDroneServiceServer) testEmbeddedByValue()                      {}

// UnsafeDroneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DroneServiceServer will
// result in compilation errors.
type UnsafeDroneServiceServer interface {
	mustEmbedUnimplementedDroneServiceServer()
}

func RegisterDroneServiceServer(s grpc.ServiceRegistrar, srv DroneServiceServer) {
	// If the following call pancis, it indicates UnimplementedDroneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DroneService_ServiceDesc, srv)
}

func _DroneService_GetApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).GetApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_GetApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).GetApplication(ctx, req.(*GetApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_SimulateFlight_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FlightSimulationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DroneServiceServer).SimulateFlight(m, &grpc.GenericServerStream[FlightSimulationRequest, Coordinates]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DroneService_SimulateFlightServer = grpc.ServerStreamingServer[Coordinates]

// DroneService_ServiceDesc is the grpc.ServiceDesc for DroneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DroneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.DroneService",
	HandlerType: (*DroneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApplication",
			Handler:    _DroneService_GetApplication_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SimulateFlight",
			Handler:       _DroneService_SimulateFlight_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/drone.proto",
}
